theme: jekyll-theme-minimal

title: BlenderFDS
description: The open user interface for the<br><a href="https://pages.nist.gov/fds-smv/">NIST Fire Dynamics Simulator (FDS)</a>
logo: https://github.com/firetools/blenderfds/wiki/p/web/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

